repos:
-   repo: local
    hooks:
    - id: rye-format
      name: rye-format
      description: "Format Python via 'rye fmt'"
      entry: rye fmt
      language: system
      types_or: [python, pyi]
      args: []
      require_serial: true
      additional_dependencies: []
      minimum_pre_commit_version: "2.9.2"

    - id: rye-lint
      name: rye-lint
      description: "Lint Python via 'rye lint'"
      entry: rye lint --fix
      language: system
      types_or: [python, pyi]
      args: []
      require_serial: true
      additional_dependencies: []
      minimum_pre_commit_version: "2.9.2"