# Generated by Django 5.2 on 2025-04-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_agentrunlog_input_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrunlog",
            name="success",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
