# Generated by Django 5.2 on 2025-04-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_agentrunlog_success"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512)),
                ("line_start", models.IntegerField()),
                ("line_end", models.IntegerField()),
                ("signature", models.TextField()),
                ("source_code", models.TextField()),
                ("docstring", models.TextField(blank=True, null=True)),
                ("comments", models.JSONField(blank=True, null=True)),
                ("string_literals", models.JSONField(blank=True, null=True)),
                ("variables", models.JSONField(blank=True, null=True)),
                ("constants", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="app_func_name_d9012f_idx"),
                    models.Index(fields=["file_path"], name="app_func_file_pa_06efa8_idx"),
                ],
                "unique_together": {("file_path", "name", "line_start")},
            },
        ),
    ]
