# Generated by Django 5.2 on 2025-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_functioninfo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AgentRunLog",
            new_name="OtelSpan",
        ),
        migrations.RenameIndex(
            model_name="functioninfo",
            new_name="app_functio_name_877854_idx",
            old_name="app_func_name_d9012f_idx",
        ),
        migrations.RenameIndex(
            model_name="functioninfo",
            new_name="app_functio_file_pa_12a69d_idx",
            old_name="app_func_file_pa_06efa8_idx",
        ),
        migrations.RemoveField(
            model_name="otelspan",
            name="success",
        ),
        migrations.AddField(
            model_name="otelspan",
            name="raw_span",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
