# Generated by Django 5.2 on 2025-04-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_rename_agentrunlog_otelspan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredrule",
            name="file_path",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoveredrule",
            name="function_name",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoveredrule",
            name="rule_type",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoveredrule",
            name="target_code_section",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
    ]
