# Generated by Django 5.2 on 2025-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_rename_agentrunlog_otelspan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyntheticDatum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("input_data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SyntheticEval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(choices=[("rules", "Rules"), ("head_to_head", "Head To Head")], max_length=20),
                ),
                ("prompt", models.TextField()),
                ("fields", models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="discoveredrule",
            name="file_path",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="discoveredrule",
            name="function_name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="discoveredrule",
            name="rule_type",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="discoveredrule",
            name="target_code_section",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="discoveredrule",
            name="rule_text",
            field=models.TextField(default=""),
        ),
    ]
