# Generated by Django 5.2 on 2025-04-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_syntheticdatum_syntheticeval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_run_id', models.CharField(db_index=True, max_length=32)),
                ('result', models.JSONField()),
                ('reward', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.syntheticdatum')),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.syntheticeval')),
            ],
        ),
    ]
