# Generated by Django 5.2 on 2025-04-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_syntheticdatum_syntheticeval_delete_discoveredrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syntheticeval",
            name="kind",
            field=models.CharField(choices=[("rules", "Rules"), ("head_to_head", "Head To Head")], max_length=20),
        ),
    ]
