# Generated by Django 5.2 on 2025-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_syntheticdatum_syntheticeval_delete_discoveredrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveredRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rule_type", models.TextField()),
                ("rule_text", models.TextField()),
                ("function_name", models.TextField()),
                ("file_path", models.TextField()),
                ("target_code_section", models.TextField()),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name="syntheticeval",
            name="kind",
            field=models.CharField(choices=[("rules", "Rules"), ("head_to_head", "Head To Head")], max_length=20),
        ),
    ]
