# Generated by Django 5.2 on 2025-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_evalrun_eval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalrun',
            name='datum',
            field=models.TextField(),
        ),
    ]
